//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.raion1 = new HashSet<raion>();
        }
    
        public int Id { get; set; }
        public int Category { get; set; }
        public int Subcategory { get; set; }
        public string naimenovanie { get; set; }
        public string adres { get; set; }
        public string telephone { get; set; }
        public int raion { get; set; }
        public string info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<raion> raion1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
